language: c
before_install:
    - sudo apt-get update
    - sudo apt-get install -y check
    - sudo apt-get install -y valgrind
compiler: gcc
script: 
    - make test
    - gcc -o main main.c spell.c dictionary.c dictionary.h
    - valgrind ./main test/test.txt wordlist.txt